# -*- coding: utf-8 -*-
"""Wine bagging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7egDfRgjjMq0O44Zv1RQrPyy1Pg6y9w
"""

from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine
wine = load_wine()
dir(wine)

x = wine.data
y = wine.target

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42 , test_size=0.2)

x_train

y_test

base = DecisionTreeClassifier()
bagging = BaggingClassifier(base, n_estimators=50, random_state=72)
bagging.fit(x_train,y_train)
y_pred = bagging.predict(x_test)
print("Accuracy score :",accuracy_score(y_test,y_pred))


plt.hist(wine.target)
plt.xlabel('Wine class')
plt.ylabel('Frequency')
plt.title('Distribution of the wine class')
plt.show()

